.

diff --git a/assets/workstation/common/dotfiles/bin/trm b/assets/workstation/common/dotfiles/bin/trm
--- a/assets/workstation/common/dotfiles/bin/trm
+++ b/assets/workstation/common/dotfiles/bin/trm
@@ -6,9 +6,24 @@
 #   - puts a shell script that restores the file to its original location if you have gpg unlock
 #     - doesn't even attempt to restore if there is a file or folder in the restore files place
 
-# fd . $@ -t f -x shred {}
-# delete the dir when donezp
+# Check if arguments are provided
+if [ $# -eq 0 ]; then
+  echo "Usage: trm <file_or_directory>..."
+  exit 1
+fi
 
-du -chs $@
+# Show the total size of the files/directories
+echo "Calculating total size..."
+du -chs "$@"
 
-\rm -ir $@
+# Ask for confirmation once
+read -p "Are you sure you want to delete these files? (y/n) " ans
+if [[ "$ans" != "y" ]]; then
+  echo "Aborting deletion."
+  exit 1
+fi
+
+# Delete files/directories recursively **without prompting for each one**
+\rm -r "$@"
+
+echo "Deletion complete."
